test: &default

  # Credentials for REST APIs
  client_id: ASXNCjje6jiqwMPQsz36xSXe5z1sNAZjUwQVym_oBEDcOp317zrdjR8Z8qVL1iI3i-vSjiKCxtwOfv-w
  client_secret: EHnJZBIWywmbfa4MG-eJunEilp-px9eknHQXaaDF7MiYgPIT2yl0VxlO78e_Vt9ZUnuqLXE0zc4WZdMv

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: casa@casa.cl
  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
